influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
  env_file:
    - 'env.influxdb'
  volumes:
    - $PWD/influxdb:/var/lib/influxdb

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  env_file:
    - 'env.grafana'
  links:
    - influxdb
  volumes:
    - $PWD/grafana:/var/lib/grafana
